# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

cluster={
  "herd.kraken.cluster" => {
    :box => "centos/7",
    :ram => 2048,
    :cpu => 2
  },
  "agent-1.kraken.cluster" => {
    :box => "centos/7",
    :ram => 2048,
    :cpu => 2
  },
  "agent-2.kraken.cluster" => {
    :box => "centos/7",
    :ram => 2048,
    :cpu => 2
  },
  "agent-3.kraken.cluster" => {
    :box => "centos/7",
    :ram => 2048,
    :cpu => 2
  },
  "agent-4.kraken.cluster" => {
    :box => "centos/7",
    :ram => 2048,
    :cpu => 2
  }
}

Vagrant.configure("2") do |config|
  # Only one rsa key for all hosts, the insecure key
  config.ssh.insert_key = false

  cluster.each_with_index do |(hostname, machine), index|
    config.vm.define hostname do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = hostname
      config.vm.provider "libvirt" do |vb|
        vb.memory = machine[:ram]
        vb.cpus = machine[:cpu]
      end # end customize

      # Use :ansible or :ansible_local to
      # select the provisioner of your choice
      if index == cluster.size - 1
        node.vm.provision :ansible do |ansible|
          ansible.compatibility_mode = '2.0'
          ansible.limit = 'all,localhost'
          ansible.playbook = "bootstrap/playbook.yml"
          #ansible.raw_arguments = ["-vvv"]
          ansible.groups = {
            "herd" => ["herd.kraken.cluster"],
            "agents" => ["agent-1.kraken.cluster", "agent-2.kraken.cluster", "agent-3.kraken.cluster", "agent-4.kraken.cluster"]
          }
        end # end provision
      end # end if
    end # end config
  end # end cluster
end # end vagrant
