# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

cluster={
  "kraken-herd" => {
    :box => "centos/7",
    :ram => 4096,
    :cpu => 4
  },
  "kraken-agent-1" => {
    :box => "centos/7",
    :ram => 2048,
    :cpu => 2
  },
  "kraken-agent-2" => {
    :box => "centos/7",
    :ram => 2048,
    :cpu => 2
  },
  "kraken-agent-3" => {
    :box => "centos/7",
    :ram => 2048,
    :cpu => 2
  },
  "kraken-agent-4" => {
    :box => "centos/7",
    :ram => 2048,
    :cpu => 2
  }
}

Vagrant.configure("2") do |config|
  # Only one rsa key for all hosts, the insecure key
  config.ssh.insert_key = false

  cluster.each_with_index do |(hostname, machine), index|
    config.vm.define hostname do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = hostname
      node.vm.provider "libvirt" do |vb|
        vb.memory = machine[:ram]
        vb.cpus = machine[:cpu]
      end # end customize

      # Use :ansible or :ansible_local to
      # select the provisioner of your choice
      if index == cluster.size - 1
        node.vm.provision :ansible do |ansible|
          ansible.limit = 'all,localhost'
          ansible.playbook = "bootstrap/playbook.yml"
          ansible.groups = {
            "agents" => ["kraken-agent-1", "kraken-agent-2", "kraken-agent-3", "kraken-agent-4"],
            "origin" => ["kraken-herd"],
            "build_index" => ["kraken-herd"],
            "tracker" => ["kraken-herd"],
            "redis" => ["kraken-herd"]
          }
        end # end provision
      end # end if
    end # end config
  end # end cluster
end # end vagrant
